src/ECard/ECardBundle/Entity/CardFile.php
<?php
namespace ECard\ECardBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * @ORM\Entity
 * @ORM\Table(name="ecard_card_files")
 * @ORM\HasLifecycleCallbacks()
 */
class CardFile
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $path;
    
    /**
     * @ORM\Column(type="string", length=5, nullable=true)
     */
    protected $type;


    /**
     * @Assert\File(
     *      maxSize="30M",
     *      mimeTypes = {
     *          "image/png",
     *          "image/jpeg",
     *          "image/jpg",
     *          "image/gif",
     *          "video/mp4",
     *      }
     * )
     * @Assert\NotNull(groups={"registration"})
     */
    protected $file;
    
    
    private $temp;
    
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set path
     *
     * @param string $path
     * @return Card
     */
    public function setPath($path)
    {
        $this->path = $path;
    
        return $this;
    }

    /**
     * Get path
     *
     * @return string 
     */
    public function getPath()
    {
        return $this->path;
    }
    
    /**
     * Returns the file type either Image or Video
     * 
     * @return string
     */
    public function getType() {
        return $this->type;
    }
    
    /**
     * Sets file.
     *
     * @param UploadedFile $file
     */
    public function setFile(UploadedFile $file = null) {
        $this->football = $file;
        $this->file = $file;
        // check if we have an old image path
        if (isset($this->path)) {
            // store the old name to delete after the update
            $this->temp = $this->path;
            $this->path = null;
        } else {
            $this->path = 'initial';
        }
    }
        
    /**
     * Get file.
     *
     * @return UploadedFile
     */
    public function getFile() {
        return $this->file;
    }

    public function getAbsolutePath() {
        return null === $this->path
            ? null
            : $this->getUploadRootDir().'/'.$this->path;
    }

    public function getWebPath() {
        return null === $this->path
            ? null
            : $this->getUploadDir().'/'.$this->path;
    }

    protected function getUploadRootDir() {
        // the absolute directory path where uploaded
        // documents should be saved
        return __DIR__.'/../../../../web/'.$this->getUploadDir();
    }

    protected function getUploadDir() {
        // get rid of the __DIR__ so it doesn't screw up
        // when displaying uploaded doc/image in the view.
        return 'uploads';
    }
    
    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload() {
        if (null !== $this->getFile()) {
            // do whatever you want to generate a unique name
            $filename = sha1(uniqid(mt_rand(), true));
            $ext = $this->getFile()->guessExtension();
            $this->path = $filename.'.'. $ext;
            if ($ext === "mp4") {
                $this->type = "video";
            }
            else {
                $this->type = "image";
            }
        }
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload() {
        if (null === $this->getFile()) {
            return;
        }

        // if there is an error when moving the file, an exception will
        // be automatically thrown by move(). This will properly prevent
        // the entity from being persisted to the database on error
        $this->getFile()->move($this->getUploadRootDir(), $this->path);

        // check if we have an old image
        if (isset($this->temp)) {
            // delete the old image
            unlink($this->getUploadRootDir().'/'.$this->temp);
            // clear the temp image path
            $this->temp = null;
        }
        $this->file = null;
    }

    /**
     * @ORM\PreRemove()
     */
    public function preRemoveUpload()
    {
        $this->temp = $this->getAbsolutePath();
    }
    
    /**
     * @ORM\PostRemove()
     */
    public function removeUpload()
    {
        if ($this->temp) {
            unlink($this->temp);
        }
    }

}

src/ECard/ECardBundle/Resources/views/Page/index_xtd.html.twig
{% extends 'ECardBundle::layout.html.twig' %}

{% block title %}ECard{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <style type='text/css'>
        @media screen and (min-width: 1px) and (max-width: 767px){
            #columns[data-columns]::before {
                content: '1 .col-xs-12';
            }
        }
        @media screen and (min-width:768px) and (max-width: 991px){
            #columns[data-columns]::before {
                content: '2 .col-sm-6';
            }
        }
        @media screen and (min-width:992px) and (max-width: 9999px){
            #columns[data-columns]::before {
                content: '3 .col-md-4';
            }
        }
    </style>
{% endblock %}

{% block coreJavascript %}
    {{ parent() }}
    <script src="{{ asset('js/salvattore.min.js') }}"></script> 
{% endblock %}


{% block body %}
    {{ parent() }}
    {% for flashMessage in app.session.flashbag.get('success') %}
        <div class="alert alert-success">{{ flashMessage }}</div>
    {% endfor %}
    <div class="panel panel-primary">
        <div class="panel-heading">
            ECard
        </div>
        <div class="panel-body">

            <div class="row">
                <div class="col-md-10">
                    {# render search bar! #}
                    {{ render(controller('ECardBundle:Search:searchBar', {'route': 'ECard_index', 
                        'category': query.category, 'readOnly': 'readonly'})) }} 
                    {% if cards %}
                        <div id="columns" data-columns>
                            {% for card in cards %}
                                <div class="panel panel-default">
                                    <div class="panel-heading">
                                        <div class="pull-right">
                                            <a href="{{ path('ECard_beginSend_card', {'id': card.id}) }}" class="btn btn-success">Send Card</a>
                                        </div>
                                        <h4>{{ card.name }}</h4>
                                    </div>
                                    <div class="panel-body">
                                        <!--div class="pull-right"-->
                                        {% if card.cardFile is defined %}
                                            {% if card.cardFile.type == "image" %}
                                                <img id="card_preview" src="{{ card.cardFile.webPath | imagine_filter('default_thumb') }}" 
                                                     class="img-responsive" alt="{{ card.name }} preview">
                                            {% else %}
                                                <video controls preload="none" poster="{{ card.cardThumb.webPath | imagine_filter('default_thumb') }}"
                                                       class="img img-responsive">
                                                    <source src="{{ asset(card.cardFile.webPath) }}" type="video/mp4">
                                                    I'm sorry; your browser doesn't support HTML5 video in WebM with VP8 or MP4 with H.264.
                                                    <!-- You can embed a Flash player here, to play your mp4 video in older browsers -->
                                                </video>
                                            {% endif %}
                                        {% endif %}

                                        <p>{{ card.description|raw }}</p>
                                    </div>
                                    <div class="panel-footer">
                                        Tags:
                                        {% for tag in card.tags %}
                                            <a href="{{ path('ECard_index', {'tags': tag}) }}" class="btn btn-xs btn-primary">{{ tag }}</a>
                                        {% endfor %}
                                    </div>
                                </div>

                            {% endfor %}
                        </div>
                    {% else %}
                        <h2 style="text-align:center;">No cards available!</h2>
                    {% endif %}

                </div>
                <div id="rightSidebar" class="col-md-2">
                    <header>
                        <h3>Tag Cloud</h3>
                    </header>
                    <p class="tags">
                        {% for tag, weight in tagWeights %}
                            <a href="{{ path('ECard_index', {'tags': tag}) }}" class="weight-{{ weight }}">{{ tag|capitalize }}</a>
                        {% else %}
                        <p>There are no tags</p>
                    {% endfor %}
                    </p>
                </div>  
            </div>
        </div>
        {% if pages > 1 %}
            <div class="panel-footer">
                <ul class="pagination">

                    {% for i in 1..pages %}
                        {% if i == 1 and i == page %}
                            <li class="disabled"><a>&laquo;</a></li>
                            {% elseif i == 1 %}
                            <li><a href="{{ path('ECard_index', query|merge({'page': (page-1)})) }}">&laquo;</a></li>
                            {% endif %}

                        {% if i == page %}
                            <li class="active"><a>{{ i }} <span class="sr-only">(current)</span></a></li>
                            {% else %}
                            <li><a href="{{ path('ECard_index', query|merge({'page': i})) }}">{{ i }}</a></li>
                            {% endif %}

                        {% if i == page and page == pages %}
                            <li class="disabled"><a>&raquo;</a></li>
                            {% elseif i == pages %}
                            <li><a href="{{ path('ECard_index', query|merge({'page': (page+1)})) }}">&raquo;</a></li>
                            {% endif %}

                    {% endfor %}
                </ul>
            </div>
        {% endif %}            
    </div>
{% endblock %}

src/ECard/ECardBundle/Resources/views/Page/public_xtd.html.twig
{% extends 'ECardBundle::layout.html.twig' %}

{% block title %}ECard{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <style type='text/css'>
        @media screen and (min-width: 1px) and (max-width: 767px){
            #columns[data-columns]::before {
                content: '1 .col-xs-12';
            }
        }
        @media screen and (min-width:768px) and (max-width: 991px){
            #columns[data-columns]::before {
                content: '2 .col-sm-6';
            }
        }
        @media screen and (min-width:992px) and (max-width: 9999px){
            #columns[data-columns]::before {
                content: '3 .col-md-4';
            }
        }
    </style>
{% endblock %}

{% block coreJavascript %}
    {{ parent() }}
    <script src="{{ asset('js/salvattore.min.js') }}"></script> 
{% endblock %}


{% block body %}
    {{ parent() }}
    {% for flashMessage in app.session.flashbag.get('success') %}
        <div class="alert alert-success">{{ flashMessage }}</div>
    {% endfor %}
    <div class="panel panel-primary">
        <div class="panel-heading">
            ECard
        </div>
        <div class="panel-body">
            
            <div class="row">
                <div class="col-md-12">
                    {# render search bar! #}
                    {{ render(controller('ECardBundle:Search:publicSearchBar', {'route': 'ECard_public',
                        'category': query.category, 'readOnly': 'readonly'})) }} 
                    {% if userCards %}
                    <div id="columns" data-columns>
                    {% for userCard in userCards %}
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-md-4">
                                        <h4>{{ userCard.card.name }}</h4>
                                    </div>
                                    <div class="col-md-5">
                                        {% if userCard.receiverUser is not null %}
                                            To: {{ userCard.receiverUser.username }}      
                                        {% elseif userCard.receiverName is not null %}
                                            To: {{ userCard.receiverName }}            
                                        {% endif %}
                                    </div>
                                    <div class="col-md-3">
                                        <a href="{{ path('ECard_public_view', {'id':userCard.uniqueId}) }}" class="btn btn-success">View</a>
                                    </div>
                                </div>
                            </div>
                            <div class="panel-body">
                                <!--div class="pull-right"-->
                                {% if userCard.card.cardFile is defined %}
                                    {% if userCard.card.cardFile.type == "image" %}
                                        <img id="card_preview" src="{{ userCard.card.cardFile.webPath | imagine_filter('default_thumb') }}" 
                                             class="img-responsive" alt="{{ userCard.card.name }} preview">
                                    {% else %}
                                        <video controls preload="none" poster="{{ userCard.card.cardThumb.webPath | imagine_filter('default_thumb') }}" 
                                               class="img img-responsive">
                                            <source src="{{ asset(userCard.card.cardFile.webPath) }}" type="video/mp4">
                                            I'm sorry; your browser doesn't support HTML5 video in WebM with VP8 or MP4 with H.264.
                                            <!-- You can embed a Flash player here, to play your mp4 video in older browsers -->
                                        </video>
                                    {% endif %}
                                {% endif %}

                                <p>{{ userCard.message }}</p>
                            </div>
                            <div class="panel-footer">
                                Tags:
                                {% for tag in userCard.card.tags %}
                                    <a href="{{ path('ECard_public', {'tags': tag}) }}" class="btn btn-xs btn-primary">{{ tag }}</a>
                                {% endfor %}
                            </div>
                        </div>
                    {% endfor %}
                    </div>
                    {% else %}
                        <h2 style="text-align:center;">No cards available!</h2>
                    {% endif %}
                </div>
            </div>
        </div>
        {% if pages > 1 %}
        <div class="panel-footer">
            <ul class="pagination">

                {% for i in 1..pages %}
                    {% if i == 1 and i == page %}
                        <li class="disabled"><a>&laquo;</a></li>
                    {% elseif i == 1 %}
                        <li><a href="{{ path('ECard_public', query|merge({'page': (page-1)})) }}">&laquo;</a></li>
                    {% endif %}

                    {% if i == page %}
                        <li class="active"><a>{{ i }} <span class="sr-only">(current)</span></a></li>
                    {% else %}
                        <li><a href="{{ path('ECard_public', query|merge({'page': i})) }}">{{ i }}</a></li>
                    {% endif %}

                    {% if i == page and page == pages %}
                        <li class="disabled"><a>&raquo;</a></li>
                    {% elseif i == pages %}
                        <li><a href="{{ path('ECard_public', query|merge({'page': (page+1)})) }}">&raquo;</a></li>
                    {% endif %}

                {% endfor %}
            </ul>
        </div>
        {% endif %}            
    </div>
{% endblock %}